Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/radar-cookbook-dev/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/radar-cookbook-dev/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/radar-cookbook-dev/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/radar-cookbook-dev/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/radar-cookbook-dev/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/radar-cookbook-dev/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/radar-cookbook-dev/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/radar-cookbook-dev/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
arm_username = os.getenv("ARM_USERNAME")
arm_password = os.getenv("ARM_PASSWORD")

datastream = "houcsapr2cfrS2.a1"

start_date = "2022-06-02T11:30:00"
end_date = "2022-06-02T11:40:00"

print(len(arm_username), len(arm_password))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 9[0m
[1;32m      6[0m start_date [38;5;241m=[39m [38;5;124m"[39m[38;5;124m2022-06-02T11:30:00[39m[38;5;124m"[39m
[1;32m      7[0m end_date [38;5;241m=[39m [38;5;124m"[39m[38;5;124m2022-06-02T11:40:00[39m[38;5;124m"[39m
[0;32m----> 9[0m [38;5;28mprint[39m([38;5;28;43mlen[39;49m[43m([49m[43marm_username[49m[43m)[49m, [38;5;28mlen[39m(arm_password))

[0;31mTypeError[0m: object of type 'NoneType' has no len()
TypeError: object of type 'NoneType' has no len()

